### ISSUE TITLE
Annotated profile plots for single profile (e.g. single sonde)

### ISSUE THREAD

**Issue by leifdenby** [eurec4a/eurec4a-environment#15]
Aim:
A function which takes a dataset, with a single height profile and produces vertical profiles

(Anna Lea please add plot)

Expected call signatures:
```python
def plot_profiles_1d(ds, variables=["T", "rh", "qv"], height_labels=["z_RHmax", "z_INV"]):
    ...
```

**Comment by annalea-albright** [comment]
![image](https://user-images.githubusercontent.com/36517345/88851154-a3464580-d1ec-11ea-9865-79351151b33c.png)
will add a script that plots choice of variables and vertical levels (somewhat like this plot)

**Comment by annalea-albright** [comment]
![image](https://user-images.githubusercontent.com/36517345/88851536-2e274000-d1ed-11ea-9e0e-1108d5668ed3.png)
will add a script that plots choice of variables and vertical levels (somewhat like this plot)

**Comment by annalea-albright** [comment]
![image](https://user-images.githubusercontent.com/36517345/88851654-5a42c100-d1ed-11ea-8349-371ad3ea0528.png)
will add a script that plots choice of variables and vertical levels (somewhat like this plot)

**Comment by annalea-albright** [comment]
(passing in either a profile, or a distribution)

**Comment by annalea-albright** [comment]
def plot_profile_1D(ds, variables, axis_labels, height_labels=None):

    # plot with 2 axes
    fig, ax1 = plt.subplots(figsize=(12,12))
    
    time_dim = "sounding"
    altitude = "height"
    # will this be addressed in dictionary? different names for altitude, etc
    
    # for now, select index at random
    index = np.random.randint(low=0, high=len(all_sondes[time_dim])-1,size=1)
    # could also plot mean + 1sigma for two variables
    
    ax1.plot(ds[variables[0]].isel({time_dim: index}).interpolate_na(dim=altitude).squeeze(), ds[altitude], linewidth=4, color='navy')
    ax1.tick_params(axis='y', labelcolor='black')
    #ax1.grid(color='navy', linestyle='-', linewidth=0.7)
    ax1.set_ylim(0,1000)
    ax1.set_xlim(50, 100) # alter these as well
    ax2 = ax1.twiny()  # instantiate a second axes that shares the same x-axis
    ax1.set_xlabel(axis_labels[0], color='navy')
    ax1.set_ylabel('altitude (m)', color='black')
    
    ax2.plot(ds[variables[1]].isel({time_dim: index}).interpolate_na(dim=altitude).squeeze(), ds[altitude], linewidth=4, color='lightblue')
    ax2.tick_params(axis='y', labelcolor='black')
    ax2.set_xlabel(axis_labels[1], color='lightblue')
    ax2.set_ylim(0,1000)
    ax2.set_xlim(8e-3, 18e-3)
    ax2.set_ylabel('altitude (m)')

    fig.tight_layout()  
    
    # pass in height_labels here
    BL_height = z_peakRH.isel({time_dim: index})
    # BL_height = ds[height_labels[0]].isel({time_dim: index})
    plt.axhline(BL_height, color='navy', linewidth=2, alpha=1 , label="mixed layer height (RHmax)")
    
    plt.gca().spines['right'].set_visible(False)
    plt.gca().spines['top'].set_visible(False)
    plt.legend(loc='best')

plot_profile_1D(ds, variables=["rh", "q"], axis_labels = ['relative humidity (%)', 'specific humidity (g/kg)'], height_labels=None)
    
@JuleRadtke, here is the code I have so far. This morning, I'm going to add the remaining functions I have to find the mixed layer height, so feel free to continue working on the plotting functions, if you are free/interested !
