### ISSUE TITLE
Add radiosonde data to data_sources.py

### ISSUE THREAD

**Issue by JuleRadtke** [eurec4a/eurec4a-environment#20]
add new datatsets like from the Radiosondes:

```python
from pathlib import Path
from datetime import datetime, timedelta

from tqdm import tqdm
import requests
import xarray as xr
import yaml

RADIOSONDES_URL =  'https://owncloud.gwdg.de/index.php/s/WUyMk92IYtzZkyf'

def open_radiosondes_dataset(level=2):
    """
    Quick-hack routine to download radiosondes dataset to local path and open it with xarray
    """
    if not level == 2:
        raise NotImplementedError(level)
    filename = _download_file(RADIOSONDES_URL)
    ds = xr.open_dataset(filename)
    return ds
```

**Comment by leifdenby** [comment]
Thanks @JuleRadtke 😄 

I just had a look at the tar-file includes different files for each instrument:
```
1.9M 28 Jun 21:20 EUREC4A_Atalante_Meteomodem-RS_L2_v2.2.0.nc
 26M 26 Jun 14:08 EUREC4A_Atalante_Vaisala-RS_L2_v2.2.0.nc
 29M 26 Jun 14:08 EUREC4A_BCO_Vaisala-RS_L2_v2.2.0.nc
 11M 26 Jun 14:08 EUREC4A_MS-Merian_Vaisala-RS_L2_v2.2.0.nc
 34M 26 Jun 14:08 EUREC4A_Meteor_Vaisala-RS_L2_v2.2.0.nc
 27M 26 Jun 14:08 EUREC4A_RonBrown_Vaisala-RS_L2_v2.2.0.nc
```

Have you been looking at all of them? I think ~150Mb is probably a bit too much to be downloading every time we run the automated tests. But if we could start with just one file that might be better

**Comment by JuleRadtke** [comment]
I looked at BCO so far, so if all are too much, I think for the repo BCO could be enough.

**Comment by leifdenby** [comment]
I've made all the radiosondes and JOANNE available via `intake` 😄, so it's really easy to add this now and we don't even have to download any files. Just need to install `intake`, `intake-xarray`, `zarr` and `s3fs`, and then you can do something like this:

```python
from intake import open_catalog
cat = open_catalog("https://raw.githubusercontent.com/leifdenby/eurec4a-intake/master/catalog.yml")
ds_rb = cat.radiosondes.ronbrown.to_dask()
ds_joanne = cat.dropsondes.to_dask()
```

I'm going to update `eurec4a_environment.data_sources` to use this instead of downloading the files directly 🚀

**Comment by leifdenby** [comment]
@JuleRadtke and @Geet-George I've added intake catalog now so that `eurec4a_environment.data_sources` uses intake for the dropsondes, and the radiosondes (and other datasets) are available through there too :)

https://github.com/eurec4a/eurec4a-environment/pull/29
