### ISSUE TITLE
Improving `get_field` of `nomenclature` module

### ISSUE THREAD

**Issue by leifdenby** [eurec4a/eurec4a-environment#32]
> Just copying over your comments @LSaffin from https://github.com/eurec4a/eurec4a-environment/pull/30#issuecomment-675971404

The changes I would make are

1. I would put the unit conversion in a separate function and module because it doesn't cover nomenclature
2. When using `get_field` in other functions it would be better to use it from `eurec4a_environment` rather than `eurec4a_environment.nomenclature`
3. Considering the first two points, it would be good to change the name of the function in nomenclature (e.g. to `get_field_by_name`) and have the function `get_field` in the top level module call that function and the function for unit conversion. Then other functions are calling this top level `get_field` and you can add other functionality that might not be related to nomenclature to it.

I can make these changes once your pull request is merged if they sound OK to you. Other questions I had:

1. Did you find any important differences between cf_units and cfunits? As far as I could tell they were basically the same but cf_units was more active and better documented.

2. Was using iris considered at all? This already does the unit checking as well as coordinate checking and better support for CF standard names (although the CF standard naming could be a limitation).

**Comment by LSaffin** [comment]
That all sounds good. I'll put together a pull request with the changes for you to approve.

That sounds like a good reason to go with `cf\_units`. I won't worry about iris either, just making sure we don't end up remaking that library.

**Comment by leifdenby** [comment]
> That sounds like a good reason to go with `cf_units`. I won't worry about iris either, just making sure we don't end up remaking that library.

Yes, definitely. We might want to start using it if we find we need more functionality that iris gives. I'll close this now since I've just merged #33. Thanks again for this
